filter:
    excluded_paths:
        - 'Documentation/*'
        - 'Tests/*'
    paths:
        - 'Classes/*'
tools:

    external_code_coverage:
        timeout: 2400
        runs: 7

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2

    php_cs_fixer:
        enabled: true

    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant:  false

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true
