#
# Table structure for table 'tt_address'
#
CREATE TABLE tt_address (
	uid int(11) unsigned NOT NULL auto_increment,
	pid int(11) unsigned DEFAULT '0' NOT NULL,
	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	gender varchar(1) DEFAULT '' NOT NULL,
	name tinytext NOT NULL,
	first_name tinytext NOT NULL,
	middle_name tinytext NOT NULL,
	last_name tinytext NOT NULL,
	birthday int(11) DEFAULT '0' NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	email varchar(255) DEFAULT '' NOT NULL,
	phone varchar(30) DEFAULT '' NOT NULL,
	mobile varchar(30) DEFAULT '' NOT NULL,
	www varchar(255) DEFAULT '' NOT NULL,
	address tinytext NOT NULL,
	building varchar(20) DEFAULT '' NOT NULL,
	room varchar(15) DEFAULT '' NOT NULL,
	company varchar(255) DEFAULT '' NOT NULL,
	position varchar(255) DEFAULT '' NOT NULL,
	city varchar(255) DEFAULT '' NOT NULL,
	zip varchar(20) DEFAULT '' NOT NULL,
	region varchar(255) DEFAULT '' NOT NULL,
	country varchar(128) DEFAULT '' NOT NULL,
	image tinyblob NOT NULL,
	fax varchar(30) DEFAULT '' NOT NULL,
	deleted tinyint(3) DEFAULT '0',
	description text NOT NULL,
	skype varchar(50) DEFAULT '' NOT NULL,
	twitter varchar(50) DEFAULT '' NOT NULL,
	facebook varchar(50) DEFAULT '' NOT NULL,
	linkedin varchar(50) DEFAULT '' NOT NULL,
	categories int(11) DEFAULT '0' NOT NULL,
	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY pid (pid,email)
);